version: '2'

services:
  postgres:
    container_name: postgresql
    restart: always
    image: postgres:alpine
    # TODO after we are done, db should only be accessed by bot
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=yatt_user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=yatt_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  bot:
    build: .
    ports:
      - "80:80"
