version: '2'

services:
  postgres:
    container_name: postgresql
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=yatt_user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=yatt_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  bot:
    image: yattbot/bots:latest
    environment:
      - TOKEN=479912516:AAH-Q10wcw7ML551IgVkuDx0HmAWpY-__FE
    ports:
      - "80:80"
    depends_on:
      - postgres
    restart: always
